workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/'

variables:
  SECURE_ANALYZERS_PREFIX: "registry.gitlab.idtice.com:7090/security/security-images"
  GITLAB_ADVANCED_SAST_ENABLED: "true"
  DS_ENFORCE_NEW_ANALYZER: "false"
  DS_MAX_DEPTH: 50
  DS_MAJOR_VERSION: "6"

include: 
  - local: templates/base/stages.yml
  - local: templates/security/secret-detection.yml
  - local: templates/security/sast.yml
  - local: templates/security/dependency-scanning.yml
